cl /EHs /MT counting.cpp
cl /EHs /MT join-detach.cpp
cl /EHs /MT threading-methods.cpp
cl /EHs /MT mutex.cpp
cl /EHs /MT timed-mutex.cpp
cl /EHs /MT recursive-mutex.cpp
cl /EHs /MT lock-guard.cpp
cl /EHs /MT unique-lock.cpp
cl /EHs /MT condition-variables.cpp
cl /EHs /MT lock.cpp
cl /EHs /MT future-promise.cpp