g++ -g counting.cpp -o counting.exe
g++ -g join-detach.cpp -o join-detach.exe
g++ -g threading-methods.cpp -o threading-methods.exe
g++ -g mutex.cpp -o mutex.exe
g++ -g timed-mutex.cpp -o timed-mutex.exe
g++ -g recursive-mutex.cpp -o recursive-mutex.exe
g++ -g lock-guard.cpp -o lock-guard.exe
g++ -g unique-lock.cpp -o unique-lock.exe
g++ -g condition-variables.cpp -o condition-variables.exe
g++ -g lock.cpp -o lock.exe
g++ -g future-promise.cpp -o future-promise.exe